config/routes.rb
Rails.application.routes.draw do
	root 'users#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  	resources :users do
  		resources :projects do
        resources :bids
      end
  	end
  	get '/login', to:'sessions#login'
  	post '/login', to: 'sessions#create'
  	post '/logout', to: 'sessions#destroy'
  	get '/logout', to: 'sessions#destroy' 

  	

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bid.rb
class Bid < ApplicationRecord
	belongs_to :project
	belongs_to :user
	validates :price, presence: true

end

app/models/project.rb
class Project < ApplicationRecord
	belongs_to :user
	has_many :bids
	validates :name, presence: true
	validates :skill, presence: true
	validates :state, presence: true
	validates :city, presence: true
end

app/models/user.rb
class User < ApplicationRecord
	has_many :projects
	has_many :bids
	validates :username, presence: true
  	validates :password, presence: true, length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
	def index
		@bids=Bid.where(project_id: params[:project_id])
		@user=User.find(params[:user_id])

	end

	def new
		@bid=Bid.new
		@user=User.find(params[:user_id])
		@project= Project.find(params[:project_id])

		
	end

	def create
		@user=User.find(params[:user_id])
		@project= Project.find(params[:project_id])
		@bid=@project.bids.create(bid_params)
		redirect_to user_project_bids_path(user_id: @user.id,project_id: @project.id)
	end

	def show
		@bid = Bid.find(params[:id])
	end
	

	private
	def bid_params
		params.require(:bid).permit(:price,:user_id,:project_id)
	end 
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	def index
		@projects=Project.all
		@user=User.find(params[:user_id])

	end
	
	def new
	 	@project=Project.new
	 	@user=User.find(params[:user_id])


	end

	def create
		@user=User.find(params[:user_id])
		@project=@user.projects.create(project_params)
		@project.save
		redirect_to user_projects_path(@user)
	end

	def show
		@project= Project.find(params[:id])
	end

	private
		def project_params
			params.require(:project).permit(:name,:skill,:state,:city,:user_id)
		end	
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def create
		@user=User.find_by(username: params[:username],password: params[:password])


		if @user.present?
			session[:user_id]=@user.id
			redirect_to @user
		else
			message="Wrong username/password"
			redirect_to login_path,notice:message
		end
	end

	def show
		@user=User.find(params[:id])
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users=User.all
	end

	def show
		@user= User.find(params[:id])
	end
	
	def new
		@user=User.new
	end

	def create
		@user=User.new(user_params)
		if @user.save
			session[:user_id]=@user.id
			message="Successfully Registered"
			redirect_to users_path,notice: message
		else
			render :new
		end
	end

	

	private

	def user_params
		params.require(:user).permit(:fullname,:role,:username,:password)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bids/index.html.erb
<h1>View Bids</h1>
<% if @bids.empty? %>
	<%= message="Bids not available" %>
<% else %>
	<% @bids.each do |bid| %>
		<%= bid.price%><br>
	<% end %>
<% end %>

app/views/bids/new.html.erb
<h1>Add bids</h1>

<%= form_for @bid, url: user_project_bids_path(user_id: @user.id,project_id: @project.id),method: :post  do |f| %>
	<%= f.label :price %>
	<%= f.hidden_field :user_id,value: @user.id %>
	<%= f.text_field :price %><br>
	<%= f.submit "Add bids"%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Loginform</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projects/index.html.erb
<h1>Projects</h1>

<ul>
	<% @projects.each do |project| %>  
      <%= project.name %><br>
      <%= project.skill %><br>
      <%= project.state %><br>
      <%= project.city %><br>
      
      <% if @user.role =="seller" %>
        <%= link_to "Add bids",new_user_project_bid_path(user_id: @user.id,project_id: project.id)%><br> <br>
      <% else %> 
      	<%= link_to "View bids",user_project_bids_path(user_id: @user.id,project_id: project.id)%><br> <br>

	    <% end %>
  <% end %>
</ul>

app/views/projects/new.html.erb
<h1>Project Details</h1>

<%#= form_for (@project,url="user_projects_path(@user)") do |f| %>
<%= form_for @project, url: user_projects_path(@user), method: :post do |f| %>

	<%= f.label :name %>
	<%= f.text_field :name %><br>
	<%= f.label :skill %>
	<%= f.text_field :skill %><br>
	<%= f.label :state %>
	<%= f.text_field :state %><br>
	<%= f.label :city %>
	<%= f.text_field :city %><br>
	<%= f.submit "Create Project"%>
<% end %>

app/views/users/index.html.erb
<p><%= notice %></p>
<h1>Welcome to my page</h1>

<%= link_to "Login",login_path %><br>

<%= link_to "New User", new_user_path %>

app/views/users/new.html.erb
<h1>Registeration Form</h1>

<%= form_for @user do |f| %>
	<%= f.label :fullname %>
	<%= f.text_field :fullname %><br>
	<%= f.label :role %>
	<%= f.select :role,["seller","buyer"] %><br>
	<%= f.label :username %>
	<%= f.text_field :username %><br>
	<%= f.label :password %>
	<%= f.password_field :password %><br>
	<%= f.submit "Create Account" %>
<% end %>

app/views/users/show.html.erb
<h1>User Details</h1>
 	<%if @user.present? %>
		<% session[:user_id]=@user.id %>
		<%= @user.fullname + " - " %>
		<%= @user.role %><br>
<% end %>
<br>
<%= link_to "Click to view project",user_projects_path(@user)%><br>
<%= link_to "Create new project",new_user_project_path(@user) %>